name: CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        service: [ user-service, payment-service, notification-service ]

    runs-on: ubuntu-latest

    env:
      GOWORK: off

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ matrix.service }}/go.mod
          cache-dependency-path: ${{ matrix.service }}/go.sum

      - name: Build
        working-directory: ${{ matrix.service }}
        run: go build ./...

      - name: Vet
        working-directory: ${{ matrix.service }}
        run: go vet ./...

      - name: Test
        working-directory: ${{ matrix.service }}
        run: go test ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: ${{ matrix.service }}
